services:
  postgres:
    image: postgres:16
    container_name: perfilprofesionalia_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: perfilprofesionalia_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:

